FROM opensearchproject/opensearch:2

# Set environment variables
ENV OPENSEARCH_INITIAL_ADMIN_PASSWORD=c3o_ZPHo!
ENV discovery.type=single-node
ENV plugins.security.disabled=true

# Expose default OpenSearch port
EXPOSE 9200